kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: assistant-front
  labels:
    app: assistant-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant-front
  template:
    metadata:
      name: assistant-front
      labels:
        app: assistant-front
    spec:
      containers:
      - name: assistant-front
        image: chatbotcustomerfacepru.azurecr.io/assistantfront:qa
---
apiVersion: v1
kind: Service
metadata:
  name: assistant-front
spec:
  ports:
  - port: 80
  selector:
    app: assistant-front